global:
  readinessRepository: oomk8s
  readinessImage: readiness-check:2.0.0
  registry:
    url: armdocker.rnd.ericsson.se
  mariadb:
    nameOverride: eric-oss-mariadb
  nexus:
    nameOverride: nexus
  hosts:
    iam: "iam.ericsson.com"
  support:
    ipv6:
      enabled: false
  iam:
    clientId: "eo"
    adminSecret: eric-sec-access-mgmt-creds
    userKey: kcadminid
    passwordKey: kcpasswd
    cacert:
      secretName: iam-cacert-secret
      key: tls.crt
      filePath: iam/ca.crt
    
imageCredentials:
  droolsImage:
    repoPath: # see default in eric-product-info.yaml
    registry:
      imagePullPolicy: IfNotPresent
  keycloakImage:
    repoPath: # see default in eric-product-info.yaml
    registry:
      imagePullPolicy: IfNotPresent

config:
  logstashServiceName: log-ls
  logstashPort: 5044

updateStrategy:
  type: RollingUpdate

#################################################################
# Application configuration defaults.
#################################################################
# application image
#repository: nexus3.onap.org:10001
#image: onap/policy-pdpd-cl:1.5.3
#pullPolicy: Always

# flag to enable debugging - application support required
debugEnabled: false

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

# probe configuration parameters
liveness:
  initialDelaySeconds: 180
  periodSeconds: 10
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 60
  periodSeconds: 10

service:
  type: ClusterIP
  name: eric-oss-pf-drools
  portName: eric-oss-pf-drools
  internalPort: 9696
  externalPort: 9696
  internalPort2: 6969
  externalPort2: 6969

ingress:
  enabled: false

# Default installation values to be overridden

server:
  jvmOpts: -server -Xms1024m -Xmx2048m

aaf:
  enabled: "false"

keystore:
  password: Pol1cy_0nap

truststore:
  password: Pol1cy_0nap

telemetry:
  user: demo@people.osaaf.org
  password: demo123456!

nexus:
  user: admin
  password: admin123
  port: 8081

db:
  user: policy_user
  password: policy_user

pap:
  user: healthcheck
  password: zb!XztG34

pdp:
  user: healthcheck
  password: zb!XztG34

aai:
  user: policy@policy.onap.org
  password: demo123456!

so:
  user: InfraPortalClient
  password: password1$

vfc:
  user:
  password:

sdnc:
  user: admin
  password: Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U

dmaap:
  brmsgw:
    key:
    password:
  pap:
    key:
    password:

resources:
  drools:
    requests:
      cpu: 100m
      memory: "1Gi"
      ephemeral-storage:
    limits:
      cpu: 1000m
      memory: "4Gi"
      ephemeral-storage:
  keycloak:
    requests:
      cpu: 100m
      memory: "1Gi"
      ephemeral-storage:
    limits:
      cpu: 1000m
      memory: "4Gi"
      ephemeral-storage:
  

labels: {}
terminationGracePeriodSeconds: 30

annotations: {}

podPriority:
  eric-oss-pf-drools:
    priorityClassName: