{{ if not .Values.global.support.ipv6.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-oss-pf-drools.name" . }}-secret
  labels:
    app: {{ template "eric-oss-pf-drools.name" . }}-secret
  {{- include "eric-oss-pf-drools.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-pf-drools.eric-product-info" .| nindent 4 }}
type: Opaque
data:
{{- range $path, $bytes := .Files.Glob "resources/secrets/*" }}
  {{ base $path }}: {{ tpl ($.Files.Get $path) $ | b64enc | quote }}
{{- end }}
{{- end }}
