{{ if not .Values.global.support.ipv6.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-oss-pf-drools.name" . }}
  labels:
    app: {{ template "eric-oss-pf-drools.name" . }}
  {{- include "eric-oss-pf-drools.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-pf-drools.eric-product-info" .| nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{if eq .Values.service.type "NodePort" -}}
    - port: {{ .Values.service.externalPort }}
      name: {{ .Values.service.portName }}-{{ .Values.service.externalPort }}
    - port: {{ .Values.service.externalPort2 }}
      name: {{ .Values.service.portName }}-{{ .Values.service.externalPort2 }}
    {{- else -}}
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: {{ .Values.service.portName }}-{{ .Values.service.externalPort }}
    - port: {{ .Values.service.externalPort2 }}
      targetPort: {{ .Values.service.internalPort2 }}
      name: {{ .Values.service.portName }}-{{ .Values.service.externalPort2 }}
    {{- end}}    
  selector:
    app: {{ .Chart.Name }}
{{- end }}
